'use client'

import { useState } from 'react'
import { ArrowRight, ArrowUpRight, Check, Copy, Menu, X } from 'lucide-react'
import { StrandsBackground } from '@/components/strands-background'
import { Reveal, Spotlight, Shimmer } from '@/components/reactbits-motion'

const providers = ['Ollama', 'OpenAI', 'Anthropic', 'Gemini', 'Azure']
const loop = [
  ['UNDERSTAND', 'Map the request to the codebase'],
  ['SEARCH', 'rg "authenticate" src/'],
  ['PLAN', '3 files affected'],
  ['EDIT', 'src/auth/middleware.ts'],
  ['RUN', 'npm test'],
  ['VERIFY', '18 passed'],
]
const tools = [
  ['Files', 'Read, create and precisely edit files.'], ['Shell', 'Run commands, tests and builds.'],
  ['Git', 'Worktrees, diffs and safe commits.'], ['Search', 'Find patterns across the codebase.'],
  ['LSP', 'Definitions, references and diagnostics.'], ['MCP', 'Connect external capabilities.'],
  ['Agents', 'Delegate focused work in parallel.'], ['Memory', 'Carry project context forward.'],
]

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="nav"><a href="/" className="brand"><span className="brand-mark">&gt;_</span> MY-CODE</a><nav className={open ? 'nav-links open' : 'nav-links'}><a href="/features">Product</a><a href="/developers">Developers</a><a href="/resources">Resources</a><a href="/community">Community</a><div className="mobile-links"><a href="/developers/quickstart">Docs <ArrowUpRight size={14} /></a><a href="/download">Download <ArrowUpRight size={14} /></a></div></nav><div className="nav-actions"><a className="nav-docs" href="/developers/quickstart">Docs</a><a className="nav-docs" href="https://github.com/your-username/my-code">GitHub</a><a className="nav-download" href="/download">Download <ArrowUpRight size={14} /></a><button className="menu-btn" onClick={() => setOpen(!open)} aria-label="Toggle navigation">{open ? <X /> : <Menu />}</button></div></header>
}

function CopyCommand({ command = 'npm install -g my-code' }: { command?: string }) {
  const [copied, setCopied] = useState(false)
  return <button className="copy-button" onClick={() => { navigator.clipboard?.writeText(command); setCopied(true); setTimeout(() => setCopied(false), 1400) }} aria-label="Copy command">{copied ? <Check size={14} /> : <Copy size={14} />} {copied ? 'copied' : 'copy'}</button>
}

function Terminal({ provider = 'Ollama' }: { provider?: string }) {
  const model = provider === 'Ollama' ? 'qwen2.5-coder' : provider === 'Anthropic' ? 'claude-sonnet' : provider === 'OpenAI' ? 'gpt-5' : provider === 'Gemini' ? 'gemini-2.5' : 'phi-4'
  return <div className="terminal-window"><div className="terminal-bar"><span className="dots"><i /><i /><i /></span><span>~/projects/acme</span><span className="terminal-model">MODEL · {model} · {provider}</span></div><div className="terminal-body"><div className="muted">~/projects/acme</div><div><b className="lime">$</b> my-code</div><div className="prompt">&gt; Find the authentication bug, fix it,<br />&nbsp;&nbsp;and run the tests.</div><div className="terminal-progress"><div><span className="lime">◉</span> Reading <b>src/auth/</b></div><div><span className="lime">◉</span> Searching <b>42 files</b></div><div><span className="lime">◉</span> Inspecting references</div><div><span className="lime">◉</span> Editing <b>middleware.ts</b></div><div><span className="lime">◉</span> Running tests <b>18 passed</b></div></div><div className="terminal-result"><span className="lime">✓</span> Authentication bug fixed<br /><span className="lime">✓</span> 18 tests passed <span className="cursor" /></div></div></div>
}

function Footer() { return <footer className="footer"><div className="footer-brand"><a href="/" className="brand"><span className="brand-mark">&gt;_</span> MY-CODE</a><p>The open, local, and extensible terminal coding agent.</p></div><div className="footer-columns"><div><b>PRODUCT</b><a href="/features">Features</a><a href="/download">Models</a><a href="/features#safety">Security</a><a href="/resources/changelog">Changelog</a></div><div><b>DEVELOPERS</b><a href="/developers/quickstart">Quick Start</a><a href="/developers/cli">CLI</a><a href="/developers/sdk">SDK</a><a href="/developers/mcp">MCP</a><a href="/developers/plugins">Plugins</a></div><div><b>COMMUNITY</b><a href="https://github.com/your-username/my-code">GitHub</a><a href="/community/contributors">Contributors</a><a href="/community/roadmap">Roadmap</a></div><div><b>RESOURCES</b><a href="/resources/docs">Docs</a><a href="/resources/blog">Blog</a><a href="/resources/changelog">Releases</a></div></div><div className="footer-bottom"><span>Open Source · MIT License</span><span>© 2026 My-Code</span></div></footer> }

export default function Home() {
  const [provider, setProvider] = useState('Ollama'); const [activeLoop, setActiveLoop] = useState(1); const [tool, setTool] = useState(0); const [terminalTab, setTerminalTab] = useState('diff'); const [permission, setPermission] = useState('DEFAULT'); const [command, setCommand] = useState('')
  return <main><Header /><section className="hero section-grid"><StrandsBackground /><div className="hero-copy"><p className="eyebrow">OPEN SOURCE <span>·</span> LOCAL-FIRST <span>·</span> TERMINAL-NATIVE</p><h1>An AI coding agent that lives <Shimmer><em>where your code does.</em></Shimmer></h1><p className="lede">Open source. Local-first. Multi-model. Fully extensible.</p><div className="hero-actions"><a className="button primary" href="/download">Install My-Code <ArrowUpRight size={16} /></a><a className="button secondary" href="https://github.com/your-username/my-code">View on GitHub <ArrowUpRight size={16} /></a></div><div className="install"><span>$ npm install -g my-code</span><CopyCommand /></div></div><div className="hero-terminal"><Terminal provider={provider} /><p className="terminal-caption"><span className="pulse" /> Agent loop active <span>·</span> developer controlled</p></div></section>
    <section className="manifesto"><p className="section-kicker">01 / LOCAL-FIRST</p><div className="manifesto-layout"><h2>Your codebase shouldn&apos;t have to leave your machine to become <em>intelligent.</em></h2><div><p>Run local models when privacy matters. Connect cloud models when you need them. Switch providers without changing your workflow.</p><div className="stack-diagram"><strong>MY-CODE</strong><span>↓</span>{['OLLAMA','OPENAI','ANTHROPIC','GEMINI','AZURE'].map(x => <span key={x}>{x}</span>)}</div><p className="lime-text">Your machine. Your models. Your rules.</p></div></div></section>
    <section className="provider-section section-grid"><div><p className="section-kicker">02 / BRING YOUR OWN INTELLIGENCE</p><h2>Switch models.<br /><em>Keep your flow.</em></h2><p className="body-copy">One agent interface for every model you trust. The provider is a detail. Your work is the constant.</p><div className="provider-tabs">{providers.map(x => <button key={x} className={provider === x ? 'active' : ''} onClick={() => setProvider(x)}>{x}<span>{provider === x ? '●' : '○'}</span></button>)}</div></div><Terminal provider={provider} /></section>
    <section className="loop-section"><div className="section-heading"><p className="section-kicker">03 / AGENTIC LOOP</p><h2>It doesn&apos;t just chat.</h2><p>It understands, plans, changes, runs, and verifies.</p></div><div className="loop-map">{loop.map(([name, detail], i) => <button key={name} className={activeLoop === i ? 'active' : ''} onClick={() => setActiveLoop(i)}><span>{String(i + 1).padStart(2, '0')}</span><b>{name}</b><small>{activeLoop === i ? detail : 'Select stage'}</small></button>)}</div><div className="loop-output"><span className="lime">$</span> {loop[activeLoop][1]}<span className="cursor" /></div></section>
    <section className="tools-section section-grid"><div className="section-heading"><p className="section-kicker">04 / EXTENSIBLE BY DEFAULT</p><h2>40+ tools.<br /><em>One agent.</em></h2><p>Capabilities become useful when they work together. Explore the system map.</p></div><div className="tool-map"><div className="tool-center">MY-CODE</div>{tools.map(([name, desc], i) => <button key={name} className={tool === i ? 'active' : ''} onMouseEnter={() => setTool(i)} onFocus={() => setTool(i)} onClick={() => setTool(i)}>{name}</button>)}</div><div className="tool-description"><b>{tools[tool][0].toUpperCase()}</b><span>{tools[tool][1]}</span></div></section>
    <section className="explorer-section"><div className="explorer-copy"><p className="section-kicker">05 / CODEBASE INTELLIGENCE</p><h2>It knows more than the file you&apos;re looking at.</h2><p>Search, references, definitions and diagnostics become one continuous path from question to change.</p><div className="intel-steps">{['Search','References','Definition','Diagnostics','Relevant files','Change'].map((x, i) => <span key={x}><b>{String(i + 1).padStart(2, '0')}</b>{x}</span>)}</div></div><pre className="code-panel">{`src/\n├── auth/\n│   ├── middleware.ts\n│   └── session.ts\n├── api/\n├── database/\n├── services/\n└── tests/\n\n$ rg "authenticate" src/\n\n→ 7 references found\n→ 3 relevant files\n→ change ready`}</pre></section>
    <section className="extension-section section-grid"><div><p className="section-kicker">06 / SHAPE THE AGENT</p><h2>Don&apos;t just use the agent.<br /><em>Shape it.</em></h2><p>Plugins, skills, hooks and MCP let you extend My-Code around the way your team actually works.</p></div><pre className="code-panel">{`.my-code/\n├── plugins/\n├── skills/\n├── hooks/\n├── mcp.json\n└── config.json`}</pre><div className="extension-list">{[['PLUGINS','Add custom tools and commands.'],['SKILLS','Create reusable workflows.'],['HOOKS','Control the agent lifecycle.'],['MCP','Connect external capabilities.']].map(([a,b]) => <div key={a}><b>{a}</b><span>{b}</span></div>)}</div></section>
    <section className="swarm-section"><div className="section-heading"><p className="section-kicker">07 / MULTI-AGENT SWARMS</p><h2>One task. <em>A team of agents.</em></h2><p>Delegate focused work, keep the main thread clear, and verify every result.</p></div><div className="swarm-network"><div className="swarm-node main">MAIN AGENT<small>Investigate the performance issue.</small></div>{[['RESEARCH','Found bottleneck in query layer.'],['CODE','Optimizing database query.'],['TEST','Running benchmark suite.'],['REVIEW','Checking regression risk.']].map(([a,b]) => <div className="swarm-node" key={a}><b>{a}</b><small>{b}</small></div>)}</div><p className="verified"><span className="lime">✓</span> Changes verified</p></section>
    <section className="memory-section"><div><p className="section-kicker">08 / MEMORY</p><h2>It remembers how you work.</h2><p>Project memory keeps useful decisions compact and available between sessions.</p></div><div className="memory-timeline"><div><b>SESSION 01</b><span>Use PostgreSQL for persistence.</span></div><div><b>SESSION 08</b><span>Follow the repository&apos;s service pattern.</span></div><div><b>SESSION 21</b><span>My-Code already knows.</span></div><div className="memory-tags"><span>Session Memory</span><span>Long-Term Memory</span><span>Project Memory</span><span>AutoDream</span></div></div></section>
    <section className="compression-section section-grid"><p className="section-kicker">09 / CONTEXT MANAGEMENT</p><h2>Long conversations.<br /><em>Short context.</em></h2><p>Four levels keep long-running sessions useful without constantly blowing through context limits.</p><div className="compression"><div><b>SNIP</b><i className="bar full" /></div><div><b>MICROCOMPACT</b><i className="bar medium" /></div><div><b>CONTEXT COLLAPSE</b><i className="bar short" /></div><div><b>AUTOCOMPACT</b><strong>SUMMARY</strong></div></div></section>
    <section className="safety-section"><div><p className="section-kicker">10 / DEVELOPER CONTROL</p><h2>Give the agent power.<br /><em>Keep the final say.</em></h2><p>Every consequential action stays visible, scoped and interruptible.</p><div className="mode-tabs">{['DEFAULT','AUTO','PLAN','BYPASS'].map(x => <button className={permission === x ? 'active' : ''} onClick={() => setPermission(x)} key={x}>{x}</button>)}</div></div><div className="permission-box"><p>Agent wants to execute:</p><code>rm -rf ./build</code><div><button>Allow</button><button className="deny">Deny</button><button>Always allow</button></div><small>Workspace Trust · Security Classification · Budget Limits</small></div></section>
    <section className="terminal-showcase section-grid"><div className="section-heading"><p className="section-kicker">11 / TERMINAL UX</p><h2>A terminal that feels like an IDE.</h2></div><div className="showcase-tabs">{['diff','markdown','tasks','usage'].map(x => <button className={terminalTab === x ? 'active' : ''} onClick={() => setTerminalTab(x)} key={x}>{x}</button>)}</div><div className="showcase-window"><div className="showcase-title">{terminalTab === 'diff' ? 'structured diff · src/users.ts' : terminalTab === 'markdown' ? 'streaming response' : terminalTab === 'tasks' ? 'active tasks' : 'session usage'}</div>{terminalTab === 'diff' ? <pre><span className="remove">- const user = await getUser()</span>{'\n'}<span className="add">+ const user = await getUserById(id)</span>{'\n\n'}<span className="lime">✓ Tests passed</span></pre> : <pre>{terminalTab === 'markdown' ? '# Authentication fix\n\nThe session boundary is now explicit.' : terminalTab === 'tasks' ? '◉ refactor query layer\n◉ run benchmark suite\n✓ review migration' : 'tokens  18.4k\ncost    local\nmodel   qwen2.5-coder'}</pre>}</div></section>
    <section className="teleport-section"><p className="section-kicker">12 / SESSION TELEPORTATION</p><h2>Start anywhere.<br /><em>Keep going anywhere.</em></h2><p>Move active sessions between machines, environments and IDEs.</p><div className="teleport-path">{['LOCAL TERMINAL','REMOTE','SSH','CLOUD','VS CODE','JETBRAINS'].map((x, i) => <div key={x}><span>{x}</span>{i < 5 && <ArrowRight />}</div>)}</div></section>
    <section className="palette-section section-grid"><div><p className="section-kicker">13 / DEVELOPER POWER</p><h2>Designed for people who live in the terminal.</h2><p>Command palette, Vim mode, worktrees and the shortcuts that keep your hands on the keyboard.</p></div><div className="palette"><input value={command} onChange={e => setCommand(e.target.value)} placeholder="/ type a command" aria-label="Command palette" />{['/model','/plan','/review','/rewind','/worktree','/agents','/memory','/mcp','/teleport'].filter(x => !command || x.includes(command)).slice(0,5).map(x => <div key={x}><b>{x}</b><span>Run command</span></div>)}</div></section>
    <section className="architecture-section"><div className="section-heading"><p className="section-kicker">14 / ARCHITECTURE</p><h2>Under the hood, it&apos;s not a wrapper.</h2></div><div className="architecture-stack">{[['ENTRY','CLI parsing and routing'],['BOOTSTRAP','Runtime state and security gates'],['CORE ENGINE','Agentic loop'],['TOOLS','40+ tools'],['SERVICES','Networking, compression, MCP, telemetry'],['UI','React terminal renderer'],['STATE','Observable application state']].map(([a,b]) => <div key={a}><b>{a}</b><span>{b}</span></div>)}</div></section>
    <section className="open-source-section section-grid"><div><p className="section-kicker">15 / OPEN SOURCE</p><h2>Built in the open.</h2><p>My-Code is open source and designed to be extended, inspected and improved by its community.</p><a className="button secondary" href="https://github.com/your-username/my-code">Explore the source <ArrowUpRight size={15} /></a></div><div className="spec-list">{['TypeScript','550+ source files','40+ tools','35+ slash commands','11 bundled skills','~40 services'].map(x => <span key={x}><b>{x.split(' ')[0]}</b>{x.substring(x.split(' ')[0].length)}</span>)}</div></section>
    <section className="comparison-section"><p className="section-kicker">16 / DIFFERENT BY DESIGN</p><h2>Built for developer control.</h2><div className="comparison-wrap"><table><thead><tr><th>Capability</th><th>My-Code</th><th>Claude Code</th><th>Cursor</th><th>Copilot</th></tr></thead><tbody>{[['Terminal','yes','yes','limited','limited'],['Local models','yes','—','—','—'],['Multi-provider','yes','—','—','—'],['Open source','yes','—','—','—'],['MCP','yes','yes','yes','yes'],['Plugins','yes','—','yes','yes'],['Multi-agent','yes','—','—','—'],['IDE bridge','yes','—','yes','yes'],['Vim mode','yes','yes','—','—'],['Session teleportation','yes','—','—','—']].map(r => <tr key={r[0]}>{r.map((x,i) => <td key={i} className={x === 'yes' ? 'yes' : ''}>{i === 0 ? x : x === 'yes' ? '✓' : x}</td>)}</tr>)}</tbody></table></div></section>
    <section className="install-section section-grid"><p className="section-kicker">17 / GET STARTED</p><h2>Your terminal is already open.</h2><p>Give it an agent.</p><div className="install-large"><span>$ npm install -g my-code</span><CopyCommand /></div><div className="hero-actions"><a className="button primary" href="/download">Install My-Code</a><a className="button secondary" href="/developers/quickstart">View Documentation</a><a className="button secondary" href="https://github.com/your-username/my-code">View GitHub</a></div><div className="platforms"><span>macOS</span><span>Linux</span><span>Windows</span></div></section><Footer /></main>
}
